version: "3.7"
services:
  reverse-proxy:
    image: traefik:v2.9
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '3000:3000'
    labels:
      - traefik.enable=true

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
